module Page.NewPost exposing (..)

import Html exposing (..)
import Html.Events exposing (..)
import Html.Attributes exposing (..)
import Data.Session exposing (Session)
import Json.Decode as Json
import Ports exposing (rmEditor, mkEditor)
import Feather
import Debug


-- MODEL


type alias Post =
    { id : Int
    , title : String
    , content : String
    , date : String
    , pristineTitle : Bool
    }


type alias Model =
    Post


initialModel : Model
initialModel =
    { id = 0
    , title = ""
    , content = ""
    , date = "just now"
    , pristineTitle = True
    }



-- UPDATE


type Msg
    = SetTitle String
    | SetContent String
    | SaveInput String


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        SetTitle t ->
            ( { model | title = t, pristineTitle = False }, Cmd.none )

        SaveInput str ->
            let
                _ =
                    Debug.log "saving" str
            in
                ( { model | title = str }, Cmd.none )

        SetContent c ->
            ( { model | content = c }, Cmd.none )



-- VIEW


view : Session -> Model -> Html Msg
view session model =
    div [ class "col mt-5 px-2" ]
        [ div [ class "float-right mr-3" ]
            [ div [ class "btn-group dropdown" ]
                [ button [ class "btn-more", type_ "button", id "dropdownMenuButton", attribute "data-toggle" "dropdown" ]
                    [ Feather.moreHorizontal "#000000" 13 ]
                , div [ class "dropdown-menu dropdown-menu-right", attribute "aria-labelledby" "dropdownMenuButton", style [ ( "width", "40rem" ) ] ]
                    [ Html.form [ class "px-4 py-3" ]
                        [ div [ class "form-group" ]
                            [ label [] [ text "Add some tags, comma-separated:" ]
                            , input [ type_ "text", class "form-control", placeholder "perl, programming, free software" ] []
                            ]
                        , div [ class "form-group" ]
                            [ label [] [ text "You can provide a summary, or it will be autogenerated:" ]
                            , textarea [ class "form-control", placeholder "Short summary..." ] []
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "mx-3" ]
            [ input [ class "h1 input-like-h1", onInput SetTitle, value model.title, placeholder "Title" ] []
            , br [] []
            , textarea [ id "mdEditor", class "form-control", onInput SetContent ] []
            , button [ class "btn btn-primary", type_ "button" ]
                [ text "Publish" ]
            , br [] []
            , br [] []
            ]
        ]


targetTitleContent : Json.Decoder String
targetTitleContent =
    Json.at [ "target", "textContent" ] Json.string
